---
name: 01 Basic Docker Build
# simplest workflow possible

on:
  push:
    # branches:
    #   - main
  pull_request:

jobs:
  build-image-result:
    name: Build Image Result
    runs-on: ubuntu-latest
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Docker build
        uses: docker/build-push-action@v6
        with:
          context: ./result  # added folder of Dockerfile in repo
          push: ${{ github.event_name != 'pull_request' }}
          tags: mihransimonian/github-action-result:latest, mihransimonian/github-action-result:01

  build-image-vote:
    name: Build Image Vote
    runs-on: ubuntu-latest
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Docker build
        uses: docker/build-push-action@v6
        with:
          context: ./vote  # added folder of Dockerfile in repo
          push: ${{ github.event_name != 'pull_request' }}
          tags: mihransimonian/github-action-vote:latest, mihransimonian/github-action-vote:01
