---
name: 01 Basic Docker Build
# simplest workflow possible

on:
  push:
    # branches:
    #   - main
  pull_request:

jobs:
  build-image-result:
    if: false # run job true/false
    name: Build Image Result
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repo
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker build
        uses: docker/build-push-action@v6
        with:
          context: ./result  # added folder of Dockerfile in repo
          push: ${{ github.event_name != 'pull_request' }}
          tags: mihransimonian/udemy-docker-masteryassignment-github-actions-img-result:${{ github.ref_name }}, mihransimonian/github-action-result:01
      - run: echo "branch name "

  build-image-vote:
    if: false # run job true/false
    name: Build Image Vote
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repo
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker build
        uses: docker/build-push-action@v6
        with:
          context: ./vote  # added folder of Dockerfile in repo
          push: ${{ github.event_name != 'pull_request' }}
          tags: mihransimonian/github-action-vote:latest, mihransimonian/github-action-vote:01
