---
name: 01 Basic Docker Build
# simplest workflow possible

on:
  push:
    # branches:
    #   - main
  pull_request:

jobs:
  build-image-result:
    if: false # run job true/false
    name: Build Image Result
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repo
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y%m%dT%H%M%S')" >> $GITHUB_ENV
      - name: Echo current date
        run: echo $NOW # Gives "20221211T014220"
      - name: Docker build
        uses: docker/build-push-action@v6
        with:
          context: ./result  # added folder of Dockerfile in repo
          push: ${{ github.event_name != 'pull_request' }}
          tags: mihransimonian/udemy-docker-masteryassignment-github-actions-result:latest, mihransimonian/udemy-docker-masteryassignment-github-actions-result:${{ github.ref_name }}-$NOW

  build-image-vote:
    if: true # run job true/false
    name: Build Image Vote
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repo
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y%m%dT%H%M%S')" >> $GITHUB_ENV
      - name: Echo current date
        run: echo $NOW # Gives "20221211T014220"
      - name: Docker build
        uses: docker/build-push-action@v6
        with:
          context: ./vote  # added folder of Dockerfile in repo
          push: ${{ github.event_name != 'pull_request' }}
          tags: mihransimonian/udemy-docker-masteryassignment-github-actions-vote:latest, mihransimonian/udemy-docker-masteryassignment-github-actions-vote:${{ github.ref_name }}${{ github.event.repository.updated_at}}-$NOW
