---
name: 04 Build with Metadata

on:
  push:
    # branches:
    #   - main
  pull_request:

jobs:
  build-image-result:
    if: true # run job true/false
    name: Build Image Result
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
#NEW: (START) ##########################################################
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: mihransimonian/udemy-dockermastery-assignment-github-actions-result
          flavor: |
            latest=false
          tags: |
            type=raw,value=04
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=ref,event=pr
            type=ref,event=branch
            type=semver,pattern={{version}}
#NEW: (END) ############################################################
      - name: Docker build
        uses: docker/build-push-action@v6
        with:
          context: ./result  # added folder of Dockerfile in repo
#NEW: (START) ##########################################################
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
#NEW: (END) ############################################################
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # comma seperated list of what OS and architechtures to build for (in parallel)
          # default is linux/amd64 (the OS of the runner) but you can add more
          # adding linux/arm64 is recommended for Apple Silicon, Raspberry Pi, AWS Graviton, etc.
          # linux/arm/v7 is for 32-bit ARM devices like Raspberry Pi 2/3
          platforms: linux/amd64,linux/arm64,linux/arm/v7

  build-image-vote:
    if: true # run job true/false
    name: Build Image Vote
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
#NEW: (START) ##########################################################
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: mihransimonian/udemy-dockermastery-assignment-github-actions-vote
          flavor: |
            latest=false
          tags: |
            type=raw,value=04
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=ref,event=pr
            type=ref,event=branch
            type=semver,pattern={{version}}
#NEW: (END) ############################################################
      - name: Docker build
        uses: docker/build-push-action@v6
        with:
          context: ./vote  # added folder of Dockerfile in repo
#NEW: (START) ##########################################################
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
#NEW: (END) ############################################################
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # comma seperated list of what OS and architechtures to build for (in parallel)
          # default is linux/amd64 (the OS of the runner) but you can add more
          # adding linux/arm64 is recommended for Apple Silicon, Raspberry Pi, AWS Graviton, etc.
          # linux/arm/v7 is for 32-bit ARM devices like Raspberry Pi 2/3
          platforms: linux/amd64,linux/arm64,linux/arm/v7

  build-image-worker:
    if: true # run job true/false
    name: Build Image Worker
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
#NEW: (START) ##########################################################
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: mihransimonian/udemy-dockermastery-assignment-github-actions-worker
          flavor: |
            latest=false
          tags: |
            type=raw,value=04
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=ref,event=pr
            type=ref,event=branch
            type=semver,pattern={{version}}
#NEW: (END) ############################################################
      - name: Docker build
        uses: docker/build-push-action@v6
        with:
          context: ./worker  # added folder of Dockerfile in repo
#NEW: (START) ##########################################################
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
#NEW: (END) ############################################################
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # comma seperated list of what OS and architechtures to build for (in parallel)
          # default is linux/amd64 (the OS of the runner) but you can add more
          # adding linux/arm64 is recommended for Apple Silicon, Raspberry Pi, AWS Graviton, etc.
          # linux/arm/v7 is for 32-bit ARM devices like Raspberry Pi 2/3
          platforms: linux/amd64,linux/arm64,linux/arm/v7
