name: 01 Basic Docker Build
run-name: ${{ github.actor }} does an ls
on: [push]

jobs:
  echo_the_folder:
    runs-on: ubuntu-latest
    steps:
      - name: set up git repo
        uses: actions/checkout@v4
      - run: ls
      - run: ls/result
