name: 01 Basic Docker Build
run-name: testing-actions
on: [push]

env:
  REPONAME: ${{ github.repository }}
  BRANCHNAME: ${{ github.ref_name }}
  GITHUB_USER: ${{ github.repository_owner }}

jobs:
  echo_the_folder:
    runs-on: ubuntu-latest
    steps:
      - name: set up git repo
        uses: actions/checkout@v4
      - run: ls
      - run: ls ./result
      - run: echo ${{ REPONAME }}
      - run: echo ${{ BRANCHNAME }}
      - run: echo ${{ GITHUB_USER }}
      - run: echo ${{ REPONAME 15:}}

